#!/usr/bin/python

# @author Edward Delaporte, http://edthedev.com
import os
import random
import sys

directory = os.path.expanduser(sys.argv[1])
print directory
files = os.listdir(directory)
print files
picture_file = random.choice(files)
picture_filename = os.path.join(dir, picture_file)
print picture_filename 
