#!/bin/bash
# Installs sun java.

# Add the repository
# Or just add this through source dialog: 
#   ppa:ferramroberto/java
# export UBUNTU_VERSION="maverick"
# export UBUNTU_VERSION="natty"
# export UBUNTU_VERSION="natty"
# export UBUNTU_VERSION="precise"
# export JAVA_VERSION="sun-java7"

# ksudo echo "deb http://archive.canonical.com/ubuntu $UBUNTU_VERSION partner" >> /etc/apt/sources.list
# sudo echo "deb https://launchpad.net/~ferramroberto/+archive/java $UBUNTU_VERSION partner" >> /etc/apt/sources.list
# sudo sed '/^#(.*partner.*\)$/\1/' < /etc/apt/sources.list > /etc/apt/sources.list
# sudo vim /etc/apt/sources.list

# Install sun java.
# sudo apt-get install sun-java6-jdk
# sudo apt-get install $JAVA_VERSION-jre
# sudo apt-get install $JAVA_VERSION-plugin

# sudo add-apt-repository ppa:webupd8team/java
# sudo apt-get update
sudo apt-get install oracle-java6-installer

# Configure it to be used...
#  This part is interactive.
# sudo update-alternatives --config java


# Run the installer
sudo echo oracle-java6-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
# sudo oracle-java6-installer

sudo update-java-alternatives -s java-6-oracle
# Remove the installer
# sudo apt-get remove oracle-java7-installer

