#!/bin/bash
echo "Reading password from ~/.dropbox-password"

passwd=`cat ~/.dropbox-password`

for file in `find ~/Dropbox/ -type 'f'|grep -E "\.crypted$"`;
    do
        dest=`echo $file|sed -e 's/\.crypted$//'`
        if [ "$dest" != "$file" ]; then
            echo -n "Decrypting $file to $dest... "
            if ( cat "$file"|mdecrypt -q -k $passwd > "$dest" ); then
                echo " OK!"
                echo " Deleting $file"
                if ( rm -f  "$file" ); then
                    echo "OK!"
                else
                    echo "Error!"
                fi
            else
                echo " Error!"
            fi
        fi
    done

rm ~/.dropbox-password
