#!/bin/bash
stty -echo
echo -n "Enter your password: "
read passwd
stty echo     # Restores screen echo.
echo
echo

for file in `find ./ -type 'f'|grep -E "\.crypted$"`;
    do
        dest=`echo $file|sed -e 's/\.crypted$//'`
        if [ "$dest" != "$file" ]; then
            echo -n "Decrypting $file to $dest... "
            if ( cat "$file"|mdecrypt -q -k $passwd > "$dest" ); then
                echo " OK!"
                echo " Deleting $file"
                if ( rm -f  "$file" ); then
                    echo "OK!"
                else
                    echo "Error!"
                fi
            else
                echo " Error!"
            fi
        fi
    done
