#!/bin/bash

echo "Copying all non-temporary documents from $HOME/Documents/ to $1/Documents"
rsync $HOME/Documents/* --recursive --progress \
    --exclude ".adobe" \
    --exclude ".Apache*" \
    --exclude ".cache" \
    --exclude ".config" \
    --exclude "Downloads" \
    --exclude ".dropbox-dist" \
    --exclude "*.dropbox*" \
    --exclude "Dropbox" \
    --exclude "*.git*" \
    --exclude "*.hg*" \
    --exclude "install" \
    --exclude "installer" \
    --exclude ".local" \
    --exclude ".minecraft" \
    --exclude ".mozilla" \
    --exclude ".shotwell" \
    --exclude "*.svn*" \
    --exclude ".thumbnails" \
    --exclude "NoBackup" \
    --exclude "Calibre Library" \
    --exclude "Music" \
    --exclude "Books" \
    --exclude "Pictures" \
    --exclude "$HOME/.*" \
    $1/Documents

