#!/usr/bin/python

# @author Edward Delaporte, http://edthedev.com
import os
import random
import subprocess

COMMAND = "/usr/bin/feh"
WP_NAMEFILE = os.path.expanduser("~/.wallpaper")
wallpaperdir = "~/Pictures/Wallpaper"
dir = os.path.expanduser(wallpaperdir)

files = os.listdir(dir)
file = random.choice(files)
wallpaper_file = os.path.join(dir, file)

# is os.path.exists(WP_N
f = open(WP_NAMEFILE,'w')
f.write(wallpaper_file)

if not os.path.exists(COMMAND):
    print "Wallpaper command %s is not installed." % COMMAND 
else:
    picture_arg = "--bg-center %s" % wallpaper_file
    subprocess.call([COMMAND, "--bg-scale", wallpaper_file])
